begin;

-- ============================================================
-- EXTENSION
-- ============================================================

create schema if not exists extensions;

create extension if not exists pgcrypto
with schema extensions;

set local search_path = public, extensions, pg_catalog, pg_temp;


-- ============================================================
-- MOBILE CONFIGURATION
-- ============================================================

create table if not exists public.bti_mobile_config (
    id smallint primary key default 1,
    office_name text not null,
    office_latitude double precision not null,
    office_longitude double precision not null,
    geofence_radius_meters double precision not null,
    max_location_accuracy_meters double precision not null,
    max_location_age_ms bigint not null,
    qr_max_age_ms bigint not null,
    qr_future_tolerance_ms bigint not null,
    session_duration_ms bigint not null,
    updated_at timestamp with time zone not null default now(),

    constraint bti_mobile_config_single_row
        check (id = 1),

    constraint bti_mobile_config_latitude_valid
        check (
            office_latitude >= -90
            and office_latitude <= 90
        ),

    constraint bti_mobile_config_longitude_valid
        check (
            office_longitude >= -180
            and office_longitude <= 180
        ),

    constraint bti_mobile_config_radius_valid
        check (geofence_radius_meters > 0),

    constraint bti_mobile_config_accuracy_valid
        check (max_location_accuracy_meters > 0),

    constraint bti_mobile_config_location_age_valid
        check (max_location_age_ms > 0),

    constraint bti_mobile_config_qr_age_valid
        check (qr_max_age_ms > 0),

    constraint bti_mobile_config_qr_tolerance_valid
        check (qr_future_tolerance_ms >= 0),

    constraint bti_mobile_config_session_duration_valid
        check (session_duration_ms > 0)
);

insert into public.bti_mobile_config (
    id,
    office_name,
    office_latitude,
    office_longitude,
    geofence_radius_meters,
    max_location_accuracy_meters,
    max_location_age_ms,
    qr_max_age_ms,
    qr_future_tolerance_ms,
    session_duration_ms,
    updated_at
)
values (
    1,
    'Kantor BTI Pontianak',
    -0.030199545602447704,
    109.32172547120854,
    50.0,
    100.0,
    30000,
    45000,
    5000,
    900000,
    now()
)
on conflict (id)
do update set
    office_name = excluded.office_name,
    office_latitude = excluded.office_latitude,
    office_longitude = excluded.office_longitude,
    geofence_radius_meters =
        excluded.geofence_radius_meters,
    max_location_accuracy_meters =
        excluded.max_location_accuracy_meters,
    max_location_age_ms =
        excluded.max_location_age_ms,
    qr_max_age_ms =
        excluded.qr_max_age_ms,
    qr_future_tolerance_ms =
        excluded.qr_future_tolerance_ms,
    session_duration_ms =
        excluded.session_duration_ms,
    updated_at = now();


-- ============================================================
-- QR REPLAY PROTECTION
-- ID disimpan sebagai text agar kompatibel dengan ID numeric/UUID.
-- ============================================================

create table if not exists public.qr_token_claims (
    qr_token text not null,
    technician_id text not null,
    attendance_type text not null,
    claimed_at timestamp with time zone not null default now(),

    constraint qr_token_claims_primary_key
        primary key (
            qr_token,
            technician_id
        ),

    constraint qr_token_claims_type_valid
        check (
            attendance_type in (
                'MASUK',
                'PULANG'
            )
        )
);

create index if not exists
    idx_qr_token_claims_technician_time
on public.qr_token_claims (
    technician_id,
    claimed_at desc
);


-- ============================================================
-- ATTENDANCE AUDIT
-- ============================================================

create table if not exists public.presensi_audit (
    id_audit bigint generated by default as identity primary key,
    request_id uuid not null default gen_random_uuid(),
    technician_id text not null,
    attendance_id text,
    device_id text,
    attendance_type text,
    qr_token text,
    latitude double precision,
    longitude double precision,
    accuracy_meters double precision,
    location_age_ms bigint,
    distance_meters double precision,
    is_mock boolean,
    result text not null,
    reason text,
    request_payload jsonb not null default '{}'::jsonb,
    created_at timestamp with time zone not null default now(),

    constraint presensi_audit_result_valid
        check (
            result in (
                'ACCEPTED',
                'REJECTED'
            )
        )
);

create index if not exists
    idx_presensi_audit_technician_time
on public.presensi_audit (
    technician_id,
    created_at desc
);

create index if not exists
    idx_presensi_audit_result_time
on public.presensi_audit (
    result,
    created_at desc
);


-- ============================================================
-- PASSWORD HASHING
-- ============================================================

create or replace function public.bti_hash_teknisi_password()
returns trigger
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $function$
begin
    if new.password is null
       or btrim(new.password) = '' then
        raise exception
            'Password teknisi tidak boleh kosong.'
            using errcode = 'P0001';
    end if;

    if new.password
       !~ '^\$2[aby]\$[0-9]{2}\$[./A-Za-z0-9]{53}$' then
        new.password := crypt(
            new.password,
            gen_salt('bf', 12)
        );
    end if;

    return new;
end;
$function$;

drop trigger if exists
    trg_bti_hash_teknisi_password
on public.teknisi;

create trigger trg_bti_hash_teknisi_password
before insert or update of password
on public.teknisi
for each row
execute function public.bti_hash_teknisi_password();


-- Mengubah password plaintext lama menjadi bcrypt.

update public.teknisi
set password = crypt(
    password,
    gen_salt('bf', 12)
)
where password is not null
  and btrim(password) <> ''
  and password
      !~ '^\$2[aby]\$[0-9]{2}\$[./A-Za-z0-9]{53}$';


-- ============================================================
-- CORE INDEXES
-- ============================================================

create unique index if not exists
    ux_teknisi_nik_normalized
on public.teknisi (
    lower(btrim(nik))
);

create index if not exists
    idx_tiket_tugas_teknisi_status_created
on public.tiket_tugas (
    id_teknisi,
    status,
    created_at desc
);

create index if not exists
    idx_log_presensi_teknisi_waktu
on public.log_presensi (
    id_teknisi,
    waktu_log desc
);


-- ============================================================
-- REMOVE INCOMPATIBLE/OLD RPC SIGNATURES
-- ============================================================

drop function if exists public.staff_login(
    text,
    text,
    text
);

drop function if exists public.staff_get_profile(
    bigint,
    text
);

drop function if exists public.staff_get_profile(
    text,
    text
);

drop function if exists public.staff_get_home(
    bigint,
    text
);

drop function if exists public.staff_get_home(
    text,
    text
);

drop function if exists public.staff_get_assignments(
    bigint,
    text,
    text
);

drop function if exists public.staff_get_assignments(
    text,
    text,
    text
);

drop function if exists public.staff_get_assignments(
    text,
    text
);

drop function if exists public.staff_update_assignment_status(
    bigint,
    text,
    bigint,
    text
);

drop function if exists public.staff_update_assignment_status(
    text,
    text,
    text,
    text
);

drop function if exists public.staff_get_attendance(
    bigint,
    text,
    integer
);

drop function if exists public.staff_get_attendance(
    text,
    text,
    text,
    text,
    integer
);

drop function if exists public.staff_submit_attendance(
    bigint,
    text,
    text,
    text,
    double precision,
    double precision,
    double precision,
    boolean,
    bigint,
    bigint
);

drop function if exists public.staff_submit_attendance(
    text,
    text,
    text,
    text,
    double precision,
    double precision,
    double precision,
    bigint,
    boolean
);


-- ============================================================
-- INTERNAL DEVICE VALIDATION
-- ============================================================

create or replace function public.bti_require_staff_device(
    p_technician_id text,
    p_device_id text
)
returns public.teknisi
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $function$
declare
    v_staff public.teknisi%rowtype;
    v_technician_id text;
    v_device_id text;
begin
    v_technician_id := nullif(
        btrim(coalesce(p_technician_id, '')),
        ''
    );

    v_device_id := nullif(
        btrim(coalesce(p_device_id, '')),
        ''
    );

    if v_technician_id is null then
        raise exception
            'Identitas teknisi tidak valid.'
            using errcode = 'P0001';
    end if;

    if v_device_id is null then
        raise exception
            'Identitas perangkat tidak tersedia.'
            using errcode = 'P0001';
    end if;

    select t.*
    into v_staff
    from public.teknisi as t
    where t.id::text = v_technician_id
    limit 1;

    if not found then
        raise exception
            'Akun teknisi tidak ditemukan.'
            using errcode = 'P0001';
    end if;

    if v_staff.device_id is null
       or btrim(v_staff.device_id) = '' then
        raise exception
            'Perangkat belum terdaftar. Silakan login kembali.'
            using errcode = 'P0001';
    end if;

    if btrim(v_staff.device_id) is distinct from v_device_id then
        raise exception
            'Akun ini telah terikat pada perangkat lain.'
            using errcode = 'P0001';
    end if;

    return v_staff;
end;
$function$;


-- ============================================================
-- INTERNAL REJECTION AUDIT
-- ============================================================

create or replace function
public.bti_reject_attendance_request(
    p_technician_id text,
    p_device_id text,
    p_attendance_type text,
    p_qr_token text,
    p_latitude double precision,
    p_longitude double precision,
    p_accuracy_meters double precision,
    p_location_age_ms bigint,
    p_distance_meters double precision,
    p_is_mock boolean,
    p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $function$
begin
    insert into public.presensi_audit (
        technician_id,
        device_id,
        attendance_type,
        qr_token,
        latitude,
        longitude,
        accuracy_meters,
        location_age_ms,
        distance_meters,
        is_mock,
        result,
        reason,
        request_payload
    )
    values (
        p_technician_id,
        p_device_id,
        p_attendance_type,
        p_qr_token,
        p_latitude,
        p_longitude,
        p_accuracy_meters,
        p_location_age_ms,
        p_distance_meters,
        p_is_mock,
        'REJECTED',
        p_reason,
        jsonb_build_object(
            'p_technician_id',
            p_technician_id,
            'p_attendance_type',
            p_attendance_type,
            'p_location_age_ms',
            p_location_age_ms
        )
    );

    return jsonb_build_object(
        'success',
        false,
        'accepted',
        false,
        'message',
        p_reason
    );
end;
$function$;


-- ============================================================
-- RPC 1: LOGIN
--
-- Android request:
-- p_nik
-- p_password
-- p_device_id
--
-- Android response:
-- id
-- nama_lengkap
-- nik
-- device_verified
-- ============================================================

create or replace function public.staff_login(
    p_nik text,
    p_password text,
    p_device_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $function$
declare
    v_staff public.teknisi%rowtype;
    v_nik text;
    v_device_id text;
begin
    v_nik := nullif(
        upper(btrim(coalesce(p_nik, ''))),
        ''
    );

    v_device_id := nullif(
        btrim(coalesce(p_device_id, '')),
        ''
    );

    if v_nik is null then
        raise exception
            'NIK wajib diisi.'
            using errcode = 'P0001';
    end if;

    if p_password is null
       or p_password = '' then
        raise exception
            'Password wajib diisi.'
            using errcode = 'P0001';
    end if;

    if v_device_id is null then
        raise exception
            'Identitas perangkat tidak tersedia.'
            using errcode = 'P0001';
    end if;

    select t.*
    into v_staff
    from public.teknisi as t
    where upper(btrim(t.nik)) = v_nik
    limit 1;

    if not found then
        raise exception
            'NIK atau password salah.'
            using errcode = 'P0001';
    end if;

    if v_staff.password is null
       or v_staff.password <> crypt(
            p_password,
            v_staff.password
       ) then
        raise exception
            'NIK atau password salah.'
            using errcode = 'P0001';
    end if;

    if v_staff.device_id is not null
       and btrim(v_staff.device_id) <> ''
       and btrim(v_staff.device_id)
           is distinct from v_device_id then
        raise exception
            'Akun ini telah terikat pada perangkat lain. Hubungi administrator untuk mereset perangkat.'
            using errcode = 'P0001';
    end if;

    if v_staff.device_id is null
       or btrim(v_staff.device_id) = '' then
        update public.teknisi
        set device_id = v_device_id
        where id = v_staff.id
        returning *
        into v_staff;
    end if;

    return jsonb_build_object(
        'success',
        true,
        'message',
        'Login berhasil.',
        'id',
        v_staff.id::text,
        'nik',
        v_staff.nik,
        'nama_lengkap',
        v_staff.nama_lengkap,
        'device_id',
        v_staff.device_id,
        'device_verified',
        true
    );
end;
$function$;


-- ============================================================
-- RPC 2: PROFILE
--
-- Android request:
-- p_technician_id
-- p_device_id
-- ============================================================

create or replace function public.staff_get_profile(
    p_technician_id text,
    p_device_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $function$
declare
    v_staff public.teknisi%rowtype;
    v_staff_json jsonb;
begin
    select *
    into v_staff
    from public.bti_require_staff_device(
        p_technician_id,
        p_device_id
    );

    v_staff_json := to_jsonb(v_staff);

    return jsonb_build_object(
        'id',
        v_staff.id::text,
        'nik',
        v_staff.nik,
        'nama_lengkap',
        v_staff.nama_lengkap,
        'jabatan',
        coalesce(
            nullif(v_staff_json ->> 'jabatan', ''),
            nullif(v_staff_json ->> 'posisi', ''),
            nullif(v_staff_json ->> 'role', ''),
            'Teknisi Lapangan'
        ),
        'no_hp',
        coalesce(
            nullif(v_staff_json ->> 'no_hp', ''),
            nullif(v_staff_json ->> 'nomor_telepon', ''),
            nullif(v_staff_json ->> 'phone', ''),
            ''
        ),
        'email',
        coalesce(
            nullif(v_staff_json ->> 'email', ''),
            nullif(v_staff_json ->> 'email_address', ''),
            ''
        ),
        'device_id',
        v_staff.device_id,
        'created_at',
        coalesce(
            v_staff_json ->> 'created_at',
            ''
        )
    );
end;
$function$;


-- ============================================================
-- RPC 3: HOME
--
-- Android response:
-- total_assignments
-- pending_assignments
-- in_progress_assignments
-- completed_assignments
-- last_attendance
-- recent_assignments
-- ============================================================

create or replace function public.staff_get_home(
    p_technician_id text,
    p_device_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $function$
declare
    v_staff public.teknisi%rowtype;

    v_total_assignments bigint;
    v_pending_assignments bigint;
    v_in_progress_assignments bigint;
    v_completed_assignments bigint;

    v_last_attendance jsonb;
    v_recent_assignments jsonb;
begin
    select *
    into v_staff
    from public.bti_require_staff_device(
        p_technician_id,
        p_device_id
    );

    select
        count(*),
        count(*) filter (
            where t.status = 'Pending'
        ),
        count(*) filter (
            where t.status = 'On Process'
        ),
        count(*) filter (
            where t.status = 'Success'
        )
    into
        v_total_assignments,
        v_pending_assignments,
        v_in_progress_assignments,
        v_completed_assignments
    from public.tiket_tugas as t
    where t.id_teknisi = v_staff.id;

    select jsonb_build_object(
        'id_absen',
        l.id_absen::text,
        'tipe_log',
        l.tipe_log,
        'waktu_log',
        l.waktu_log,
        'latitude_aktual',
        l.latitude_aktual,
        'longitude_aktual',
        l.longitude_aktual,
        'is_valid',
        l.is_valid
    )
    into v_last_attendance
    from public.log_presensi as l
    where l.id_teknisi = v_staff.id
    order by
        l.waktu_log desc,
        l.id_absen desc
    limit 1;

    select coalesce(
        jsonb_agg(
            assignment_item
            order by assignment_created_at desc
        ),
        '[]'::jsonb
    )
    into v_recent_assignments
    from (
        select
            jsonb_build_object(
                'id',
                t.id_tugas::text,
                'id_tugas',
                t.id_tugas::text,
                'nama_klien',
                t.nama_klien,
                'alamat_klien',
                t.alamat_klien,
                'status',
                t.status,
                'created_at',
                t.created_at
            ) as assignment_item,
            t.created_at as assignment_created_at
        from public.tiket_tugas as t
        where t.id_teknisi = v_staff.id
        order by t.created_at desc
        limit 5
    ) as recent_rows;

    return jsonb_build_object(
        'total_assignments',
        coalesce(v_total_assignments, 0),
        'pending_assignments',
        coalesce(v_pending_assignments, 0),
        'in_progress_assignments',
        coalesce(v_in_progress_assignments, 0),
        'completed_assignments',
        coalesce(v_completed_assignments, 0),
        'last_attendance',
        coalesce(
            v_last_attendance,
            '{}'::jsonb
        ),
        'recent_assignments',
        coalesce(
            v_recent_assignments,
            '[]'::jsonb
        )
    );
end;
$function$;


-- ============================================================
-- RPC 4: ASSIGNMENT LIST
--
-- Android request:
-- p_technician_id
-- p_device_id
-- ============================================================

create or replace function public.staff_get_assignments(
    p_technician_id text,
    p_device_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $function$
declare
    v_staff public.teknisi%rowtype;
    v_assignments jsonb;
begin
    select *
    into v_staff
    from public.bti_require_staff_device(
        p_technician_id,
        p_device_id
    );

    select coalesce(
        jsonb_agg(
            assignment_item
            order by assignment_created_at desc
        ),
        '[]'::jsonb
    )
    into v_assignments
    from (
        select
            jsonb_build_object(
                'id',
                t.id_tugas::text,
                'id_tugas',
                t.id_tugas::text,
                'nama_klien',
                t.nama_klien,
                'alamat_klien',
                t.alamat_klien,
                'latitude_klien',
                t.latitude_klien,
                'longitude_klien',
                t.longitude_klien,
                'status',
                t.status,
                'created_at',
                t.created_at
            ) as assignment_item,
            t.created_at as assignment_created_at
        from public.tiket_tugas as t
        where t.id_teknisi = v_staff.id
    ) as assignment_rows;

    return v_assignments;
end;
$function$;


-- ============================================================
-- RPC 5: UPDATE ASSIGNMENT STATUS
--
-- Android request:
-- p_technician_id
-- p_device_id
-- p_assignment_id
-- p_new_status
-- ============================================================

create or replace function
public.staff_update_assignment_status(
    p_technician_id text,
    p_device_id text,
    p_assignment_id text,
    p_new_status text
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $function$
declare
    v_staff public.teknisi%rowtype;
    v_assignment public.tiket_tugas%rowtype;
    v_assignment_id text;
    v_new_status text;
begin
    select *
    into v_staff
    from public.bti_require_staff_device(
        p_technician_id,
        p_device_id
    );

    v_assignment_id := nullif(
        btrim(coalesce(p_assignment_id, '')),
        ''
    );

    v_new_status :=
        case lower(
            btrim(coalesce(p_new_status, ''))
        )
            when 'on process'
                then 'On Process'
            when 'success'
                then 'Success'
            else null
        end;

    if v_assignment_id is null then
        raise exception
            'ID penugasan tidak valid.'
            using errcode = 'P0001';
    end if;

    if v_new_status is null then
        raise exception
            'Status tujuan tidak didukung.'
            using errcode = 'P0001';
    end if;

    select t.*
    into v_assignment
    from public.tiket_tugas as t
    where t.id_tugas::text = v_assignment_id
      and t.id_teknisi = v_staff.id
    for update;

    if not found then
        raise exception
            'Penugasan tidak ditemukan atau bukan milik akun ini.'
            using errcode = 'P0001';
    end if;

    if v_assignment.status = 'Success' then
        return jsonb_build_object(
            'success',
            false,
            'accepted',
            false,
            'message',
            'Penugasan yang sudah selesai tidak dapat diubah kembali.'
        );
    end if;

    if v_assignment.status = 'Pending'
       and v_new_status = 'Success' then
        return jsonb_build_object(
            'success',
            false,
            'accepted',
            false,
            'message',
            'Penugasan harus diproses terlebih dahulu sebelum diselesaikan.'
        );
    end if;

    if v_assignment.status = 'On Process'
       and v_new_status = 'On Process' then
        return jsonb_build_object(
            'success',
            true,
            'accepted',
            true,
            'message',
            'Penugasan sudah berstatus On Process.',
            'status',
            v_assignment.status
        );
    end if;

    update public.tiket_tugas
    set status = v_new_status
    where id_tugas = v_assignment.id_tugas
      and id_teknisi = v_staff.id
    returning *
    into v_assignment;

    return jsonb_build_object(
        'success',
        true,
        'accepted',
        true,
        'message',
        'Status penugasan berhasil diperbarui.',
        'id',
        v_assignment.id_tugas::text,
        'id_tugas',
        v_assignment.id_tugas::text,
        'status',
        v_assignment.status
    );
end;
$function$;


-- ============================================================
-- RPC 6: ATTENDANCE HISTORY
--
-- Android request:
-- p_technician_id
-- p_device_id
-- p_start_at
-- p_end_at
-- p_limit
-- ============================================================

create or replace function public.staff_get_attendance(
    p_technician_id text,
    p_device_id text,
    p_start_at text,
    p_end_at text,
    p_limit integer
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $function$
declare
    v_staff public.teknisi%rowtype;
    v_start_at timestamp with time zone;
    v_end_at timestamp with time zone;
    v_end_exclusive boolean := false;
    v_limit integer;
    v_records jsonb;
begin
    select *
    into v_staff
    from public.bti_require_staff_device(
        p_technician_id,
        p_device_id
    );

    v_limit := greatest(
        1,
        least(
            coalesce(p_limit, 30),
            100
        )
    );

    if nullif(
        btrim(coalesce(p_start_at, '')),
        ''
    ) is not null then
        begin
            if btrim(p_start_at)
               ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' then
                v_start_at := (
                    btrim(p_start_at)::date::timestamp
                    at time zone 'Asia/Pontianak'
                );
            else
                v_start_at :=
                    btrim(p_start_at)::timestamp with time zone;
            end if;
        exception
            when others then
                raise exception
                    'Format tanggal awal tidak valid.'
                    using errcode = 'P0001';
        end;
    end if;

    if nullif(
        btrim(coalesce(p_end_at, '')),
        ''
    ) is not null then
        begin
            if btrim(p_end_at)
               ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' then
                v_end_at := (
                    (
                        btrim(p_end_at)::date + 1
                    )::timestamp
                    at time zone 'Asia/Pontianak'
                );

                v_end_exclusive := true;
            else
                v_end_at :=
                    btrim(p_end_at)::timestamp with time zone;

                v_end_exclusive := false;
            end if;
        exception
            when others then
                raise exception
                    'Format tanggal akhir tidak valid.'
                    using errcode = 'P0001';
        end;
    end if;

    if v_start_at is not null
       and v_end_at is not null
       and v_start_at >= v_end_at then
        raise exception
            'Rentang tanggal presensi tidak valid.'
            using errcode = 'P0001';
    end if;

    select coalesce(
        jsonb_agg(
            attendance_item
            order by attendance_time desc
        ),
        '[]'::jsonb
    )
    into v_records
    from (
        select
            jsonb_build_object(
                'id',
                l.id_absen::text,
                'id_absen',
                l.id_absen::text,
                'tipe_log',
                l.tipe_log,
                'waktu_log',
                l.waktu_log,
                'latitude_aktual',
                l.latitude_aktual,
                'longitude_aktual',
                l.longitude_aktual,
                'is_valid',
                l.is_valid
            ) as attendance_item,
            l.waktu_log as attendance_time
        from public.log_presensi as l
        where l.id_teknisi = v_staff.id
          and (
                v_start_at is null
                or l.waktu_log >= v_start_at
              )
          and (
                v_end_at is null
                or (
                    v_end_exclusive
                    and l.waktu_log < v_end_at
                )
                or (
                    not v_end_exclusive
                    and l.waktu_log <= v_end_at
                )
              )
        order by
            l.waktu_log desc,
            l.id_absen desc
        limit v_limit
    ) as attendance_rows;

    return v_records;
end;
$function$;


-- ============================================================
-- RPC 7: SUBMIT ATTENDANCE
--
-- Android request:
-- p_technician_id
-- p_device_id
-- p_attendance_type
-- p_qr_payload
-- p_latitude
-- p_longitude
-- p_accuracy_meters
-- p_location_age_ms
-- p_is_mock
--
-- Android response:
-- accepted
-- message
-- ============================================================

create or replace function public.staff_submit_attendance(
    p_technician_id text,
    p_device_id text,
    p_attendance_type text,
    p_qr_payload text,
    p_latitude double precision,
    p_longitude double precision,
    p_accuracy_meters double precision,
    p_location_age_ms bigint,
    p_is_mock boolean
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $function$
declare
    v_staff public.teknisi%rowtype;
    v_config public.bti_mobile_config%rowtype;

    v_attendance_type text;
    v_qr_payload text;
    v_qr_uuid text;
    v_qr_time_text text;
    v_qr_time_ms bigint;
    v_active_qr_token text;

    v_server_time_ms bigint;
    v_qr_age_ms bigint;
    v_distance_meters double precision;

    v_last_today_type text;
    v_claimed_count integer;

    v_attendance_id text;
    v_attendance_time timestamp with time zone;
begin
    select *
    into v_staff
    from public.bti_require_staff_device(
        p_technician_id,
        p_device_id
    );

    select c.*
    into v_config
    from public.bti_mobile_config as c
    where c.id = 1;

    if not found then
        raise exception
            'Konfigurasi aplikasi mobile belum tersedia.'
            using errcode = 'P0001';
    end if;

    v_attendance_type := upper(
        btrim(coalesce(p_attendance_type, ''))
    );

    v_qr_payload := btrim(
        coalesce(p_qr_payload, '')
    );

    if v_attendance_type not in (
        'MASUK',
        'PULANG'
    ) then
        return public.bti_reject_attendance_request(
            v_staff.id::text,
            p_device_id,
            v_attendance_type,
            v_qr_payload,
            p_latitude,
            p_longitude,
            p_accuracy_meters,
            p_location_age_ms,
            null,
            p_is_mock,
            'Jenis presensi tidak valid.'
        );
    end if;

    if p_is_mock is null
       or p_is_mock then
        return public.bti_reject_attendance_request(
            v_staff.id::text,
            p_device_id,
            v_attendance_type,
            v_qr_payload,
            p_latitude,
            p_longitude,
            p_accuracy_meters,
            p_location_age_ms,
            null,
            p_is_mock,
            'Lokasi palsu atau mock location terdeteksi.'
        );
    end if;

    if p_latitude is null
       or p_longitude is null
       or p_latitude < -90
       or p_latitude > 90
       or p_longitude < -180
       or p_longitude > 180 then
        return public.bti_reject_attendance_request(
            v_staff.id::text,
            p_device_id,
            v_attendance_type,
            v_qr_payload,
            p_latitude,
            p_longitude,
            p_accuracy_meters,
            p_location_age_ms,
            null,
            p_is_mock,
            'Koordinat lokasi tidak valid.'
        );
    end if;

    if p_accuracy_meters is null
       or p_accuracy_meters < 0
       or p_accuracy_meters >
          v_config.max_location_accuracy_meters then
        return public.bti_reject_attendance_request(
            v_staff.id::text,
            p_device_id,
            v_attendance_type,
            v_qr_payload,
            p_latitude,
            p_longitude,
            p_accuracy_meters,
            p_location_age_ms,
            null,
            p_is_mock,
            'Akurasi lokasi belum memenuhi batas yang diizinkan.'
        );
    end if;

    if p_location_age_ms is null
       or p_location_age_ms < 0 then
        return public.bti_reject_attendance_request(
            v_staff.id::text,
            p_device_id,
            v_attendance_type,
            v_qr_payload,
            p_latitude,
            p_longitude,
            p_accuracy_meters,
            p_location_age_ms,
            null,
            p_is_mock,
            'Usia data lokasi tidak valid.'
        );
    end if;

    if p_location_age_ms >
       v_config.max_location_age_ms then
        return public.bti_reject_attendance_request(
            v_staff.id::text,
            p_device_id,
            v_attendance_type,
            v_qr_payload,
            p_latitude,
            p_longitude,
            p_accuracy_meters,
            p_location_age_ms,
            null,
            p_is_mock,
            'Data lokasi sudah terlalu lama. Perbarui lokasi dan coba kembali.'
        );
    end if;

    if v_qr_payload = ''
       or array_length(
            string_to_array(
                v_qr_payload,
                '|'
            ),
            1
          ) <> 2 then
        return public.bti_reject_attendance_request(
            v_staff.id::text,
            p_device_id,
            v_attendance_type,
            v_qr_payload,
            p_latitude,
            p_longitude,
            p_accuracy_meters,
            p_location_age_ms,
            null,
            p_is_mock,
            'Format QR Code tidak valid.'
        );
    end if;

    v_qr_uuid := split_part(
        v_qr_payload,
        '|',
        1
    );

    v_qr_time_text := split_part(
        v_qr_payload,
        '|',
        2
    );

    if v_qr_uuid
       !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
       or v_qr_time_text
          !~ '^[0-9]{10,16}$' then
        return public.bti_reject_attendance_request(
            v_staff.id::text,
            p_device_id,
            v_attendance_type,
            v_qr_payload,
            p_latitude,
            p_longitude,
            p_accuracy_meters,
            p_location_age_ms,
            null,
            p_is_mock,
            'Format token QR Code tidak valid.'
        );
    end if;

    begin
        v_qr_time_ms :=
            v_qr_time_text::bigint;
    exception
        when invalid_text_representation
          or numeric_value_out_of_range then
            return public.bti_reject_attendance_request(
                v_staff.id::text,
                p_device_id,
                v_attendance_type,
                v_qr_payload,
                p_latitude,
                p_longitude,
                p_accuracy_meters,
                p_location_age_ms,
                null,
                p_is_mock,
                'Waktu token QR Code tidak valid.'
            );
    end;

    v_server_time_ms := floor(
        extract(
            epoch from clock_timestamp()
        ) * 1000
    )::bigint;

    v_qr_age_ms :=
        v_server_time_ms -
        v_qr_time_ms;

    if v_qr_age_ms <
       -v_config.qr_future_tolerance_ms then
        return public.bti_reject_attendance_request(
            v_staff.id::text,
            p_device_id,
            v_attendance_type,
            v_qr_payload,
            p_latitude,
            p_longitude,
            p_accuracy_meters,
            p_location_age_ms,
            null,
            p_is_mock,
            'Token QR Code berasal dari waktu yang tidak valid.'
        );
    end if;

    if v_qr_age_ms >
       v_config.qr_max_age_ms then
        return public.bti_reject_attendance_request(
            v_staff.id::text,
            p_device_id,
            v_attendance_type,
            v_qr_payload,
            p_latitude,
            p_longitude,
            p_accuracy_meters,
            p_location_age_ms,
            null,
            p_is_mock,
            'Token QR Code sudah kedaluwarsa.'
        );
    end if;

    select to_jsonb(q) ->> 'token'
    into v_active_qr_token
    from public.qr_aktif as q
    where q.id::text = '1'
    limit 1;

    if v_active_qr_token is null
       or btrim(v_active_qr_token) = '' then
        return public.bti_reject_attendance_request(
            v_staff.id::text,
            p_device_id,
            v_attendance_type,
            v_qr_payload,
            p_latitude,
            p_longitude,
            p_accuracy_meters,
            p_location_age_ms,
            null,
            p_is_mock,
            'Token QR aktif belum tersedia.'
        );
    end if;

    if btrim(v_active_qr_token)
       is distinct from v_qr_payload then
        return public.bti_reject_attendance_request(
            v_staff.id::text,
            p_device_id,
            v_attendance_type,
            v_qr_payload,
            p_latitude,
            p_longitude,
            p_accuracy_meters,
            p_location_age_ms,
            null,
            p_is_mock,
            'Token QR Code sudah tidak aktif.'
        );
    end if;

    v_distance_meters :=
        2.0 * 6371000.0 * asin(
            sqrt(
                least(
                    1.0,
                    power(
                        sin(
                            radians(
                                p_latitude -
                                v_config.office_latitude
                            ) / 2.0
                        ),
                        2
                    )
                    +
                    cos(
                        radians(
                            v_config.office_latitude
                        )
                    )
                    *
                    cos(
                        radians(p_latitude)
                    )
                    *
                    power(
                        sin(
                            radians(
                                p_longitude -
                                v_config.office_longitude
                            ) / 2.0
                        ),
                        2
                    )
                )
            )
        );

    if v_distance_meters >
       v_config.geofence_radius_meters then
        return public.bti_reject_attendance_request(
            v_staff.id::text,
            p_device_id,
            v_attendance_type,
            v_qr_payload,
            p_latitude,
            p_longitude,
            p_accuracy_meters,
            p_location_age_ms,
            v_distance_meters,
            p_is_mock,
            format(
                'Anda berada di luar area kantor. Jarak saat ini sekitar %s meter.',
                round(v_distance_meters)::bigint
            )
        );
    end if;

    select l.tipe_log
    into v_last_today_type
    from public.log_presensi as l
    where l.id_teknisi = v_staff.id
      and timezone(
            'Asia/Pontianak',
            l.waktu_log
          )::date =
          timezone(
            'Asia/Pontianak',
            now()
          )::date
    order by
        l.waktu_log desc,
        l.id_absen desc
    limit 1;

    if v_last_today_type is null
       and v_attendance_type <> 'MASUK' then
        return public.bti_reject_attendance_request(
            v_staff.id::text,
            p_device_id,
            v_attendance_type,
            v_qr_payload,
            p_latitude,
            p_longitude,
            p_accuracy_meters,
            p_location_age_ms,
            v_distance_meters,
            p_is_mock,
            'Anda harus melakukan presensi masuk terlebih dahulu.'
        );
    end if;

    if v_last_today_type = 'MASUK'
       and v_attendance_type <> 'PULANG' then
        return public.bti_reject_attendance_request(
            v_staff.id::text,
            p_device_id,
            v_attendance_type,
            v_qr_payload,
            p_latitude,
            p_longitude,
            p_accuracy_meters,
            p_location_age_ms,
            v_distance_meters,
            p_is_mock,
            'Presensi masuk hari ini sudah tercatat.'
        );
    end if;

    if v_last_today_type = 'PULANG' then
        return public.bti_reject_attendance_request(
            v_staff.id::text,
            p_device_id,
            v_attendance_type,
            v_qr_payload,
            p_latitude,
            p_longitude,
            p_accuracy_meters,
            p_location_age_ms,
            v_distance_meters,
            p_is_mock,
            'Presensi hari ini sudah selesai.'
        );
    end if;

    insert into public.qr_token_claims (
        qr_token,
        technician_id,
        attendance_type,
        claimed_at
    )
    values (
        v_qr_payload,
        v_staff.id::text,
        v_attendance_type,
        clock_timestamp()
    )
    on conflict (
        qr_token,
        technician_id
    )
    do nothing;

    get diagnostics
        v_claimed_count = row_count;

    if v_claimed_count = 0 then
        return public.bti_reject_attendance_request(
            v_staff.id::text,
            p_device_id,
            v_attendance_type,
            v_qr_payload,
            p_latitude,
            p_longitude,
            p_accuracy_meters,
            p_location_age_ms,
            v_distance_meters,
            p_is_mock,
            'Token QR Code ini sudah pernah digunakan.'
        );
    end if;

    insert into public.log_presensi (
        id_teknisi,
        waktu_log,
        tipe_log,
        latitude_aktual,
        longitude_aktual,
        is_valid
    )
    values (
        v_staff.id,
        clock_timestamp(),
        v_attendance_type,
        p_latitude,
        p_longitude,
        true
    )
    returning
        id_absen::text,
        waktu_log
    into
        v_attendance_id,
        v_attendance_time;

    insert into public.presensi_audit (
        technician_id,
        attendance_id,
        device_id,
        attendance_type,
        qr_token,
        latitude,
        longitude,
        accuracy_meters,
        location_age_ms,
        distance_meters,
        is_mock,
        result,
        reason,
        request_payload
    )
    values (
        v_staff.id::text,
        v_attendance_id,
        p_device_id,
        v_attendance_type,
        v_qr_payload,
        p_latitude,
        p_longitude,
        p_accuracy_meters,
        p_location_age_ms,
        v_distance_meters,
        p_is_mock,
        'ACCEPTED',
        'Presensi diterima.',
        jsonb_build_object(
            'p_technician_id',
            v_staff.id::text,
            'p_attendance_type',
            v_attendance_type,
            'p_location_age_ms',
            p_location_age_ms
        )
    );

    return jsonb_build_object(
        'success',
        true,
        'accepted',
        true,
        'message',
        case
            when v_attendance_type = 'MASUK'
                then 'Presensi masuk berhasil.'
            else 'Presensi pulang berhasil.'
        end,
        'id',
        v_attendance_id,
        'id_absen',
        v_attendance_id,
        'tipe_log',
        v_attendance_type,
        'waktu_log',
        v_attendance_time,
        'latitude_aktual',
        p_latitude,
        'longitude_aktual',
        p_longitude,
        'accuracy_meters',
        p_accuracy_meters,
        'distance_meters',
        v_distance_meters,
        'is_valid',
        true
    );
end;
$function$;


-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================

alter table public.teknisi
    enable row level security;

alter table public.tiket_tugas
    enable row level security;

alter table public.log_presensi
    enable row level security;

alter table public.qr_aktif
    enable row level security;

alter table public.token_qr_hangus
    enable row level security;

alter table public.bti_mobile_config
    enable row level security;

alter table public.qr_token_claims
    enable row level security;

alter table public.presensi_audit
    enable row level security;


-- ============================================================
-- AUTHENTICATED DASHBOARD POLICIES
-- ============================================================

drop policy if exists
    teknisi_authenticated_all
on public.teknisi;

drop policy if exists
    tiket_tugas_authenticated_all
on public.tiket_tugas;

drop policy if exists
    log_presensi_authenticated_all
on public.log_presensi;

drop policy if exists
    qr_aktif_authenticated_all
on public.qr_aktif;

drop policy if exists
    token_qr_hangus_authenticated_all
on public.token_qr_hangus;

drop policy if exists
    bti_mobile_config_authenticated_all
on public.bti_mobile_config;

drop policy if exists
    qr_token_claims_authenticated_select
on public.qr_token_claims;

drop policy if exists
    presensi_audit_authenticated_select
on public.presensi_audit;


create policy teknisi_authenticated_all
on public.teknisi
for all
to authenticated
using (true)
with check (true);

create policy tiket_tugas_authenticated_all
on public.tiket_tugas
for all
to authenticated
using (true)
with check (true);

create policy log_presensi_authenticated_all
on public.log_presensi
for all
to authenticated
using (true)
with check (true);

create policy qr_aktif_authenticated_all
on public.qr_aktif
for all
to authenticated
using (true)
with check (true);

create policy token_qr_hangus_authenticated_all
on public.token_qr_hangus
for all
to authenticated
using (true)
with check (true);

create policy bti_mobile_config_authenticated_all
on public.bti_mobile_config
for all
to authenticated
using (true)
with check (true);

create policy qr_token_claims_authenticated_select
on public.qr_token_claims
for select
to authenticated
using (true);

create policy presensi_audit_authenticated_select
on public.presensi_audit
for select
to authenticated
using (true);


-- ============================================================
-- TABLE PRIVILEGES
-- ============================================================

revoke all privileges
on table public.teknisi
from public, anon;

revoke all privileges
on table public.tiket_tugas
from public, anon;

revoke all privileges
on table public.log_presensi
from public, anon;

revoke all privileges
on table public.qr_aktif
from public, anon;

revoke all privileges
on table public.token_qr_hangus
from public, anon;

revoke all privileges
on table public.bti_mobile_config
from public, anon;

revoke all privileges
on table public.qr_token_claims
from public, anon;

revoke all privileges
on table public.presensi_audit
from public, anon;


grant select, insert, update, delete
on table public.teknisi
to authenticated;

grant select, insert, update, delete
on table public.tiket_tugas
to authenticated;

grant select, insert, update, delete
on table public.log_presensi
to authenticated;

grant select, insert, update, delete
on table public.qr_aktif
to authenticated;

grant select, insert, update, delete
on table public.token_qr_hangus
to authenticated;

grant select, insert, update, delete
on table public.bti_mobile_config
to authenticated;

grant select
on table public.qr_token_claims
to authenticated;

grant select
on table public.presensi_audit
to authenticated;

grant usage, select
on all sequences in schema public
to authenticated;


-- ============================================================
-- FUNCTION PRIVILEGES
-- ============================================================

revoke all
on function public.bti_hash_teknisi_password()
from public, anon, authenticated;

revoke all
on function public.bti_require_staff_device(
    text,
    text
)
from public, anon, authenticated;

revoke all
on function public.bti_reject_attendance_request(
    text,
    text,
    text,
    text,
    double precision,
    double precision,
    double precision,
    bigint,
    double precision,
    boolean,
    text
)
from public, anon, authenticated;


revoke all
on function public.staff_login(
    text,
    text,
    text
)
from public, anon, authenticated;

revoke all
on function public.staff_get_profile(
    text,
    text
)
from public, anon, authenticated;

revoke all
on function public.staff_get_home(
    text,
    text
)
from public, anon, authenticated;

revoke all
on function public.staff_get_assignments(
    text,
    text
)
from public, anon, authenticated;

revoke all
on function public.staff_update_assignment_status(
    text,
    text,
    text,
    text
)
from public, anon, authenticated;

revoke all
on function public.staff_get_attendance(
    text,
    text,
    text,
    text,
    integer
)
from public, anon, authenticated;

revoke all
on function public.staff_submit_attendance(
    text,
    text,
    text,
    text,
    double precision,
    double precision,
    double precision,
    bigint,
    boolean
)
from public, anon, authenticated;


grant execute
on function public.staff_login(
    text,
    text,
    text
)
to anon, authenticated;

grant execute
on function public.staff_get_profile(
    text,
    text
)
to anon, authenticated;

grant execute
on function public.staff_get_home(
    text,
    text
)
to anon, authenticated;

grant execute
on function public.staff_get_assignments(
    text,
    text
)
to anon, authenticated;

grant execute
on function public.staff_update_assignment_status(
    text,
    text,
    text,
    text
)
to anon, authenticated;

grant execute
on function public.staff_get_attendance(
    text,
    text,
    text,
    text,
    integer
)
to anon, authenticated;

grant execute
on function public.staff_submit_attendance(
    text,
    text,
    text,
    text,
    double precision,
    double precision,
    double precision,
    bigint,
    boolean
)
to anon, authenticated;


notify pgrst, 'reload schema';

commit;